Feature/pci 4 compatibility
aligent/magento2-pci-4-compatibility pull request #1
Opened 2024-12-31 03:52 UTC by aligent-lturner

WIP

2025-01-02 23:52 UTC, dominicaligent requested changes

2025-01-02 23:52 UTC, dominicaligent commented on Model/DisableInactiveAdminAccounts.php
> +        $userCollection->addFieldToFilter('logdate', ['null' => true]);
Instead of using two collections, can we use a single collection with an OR condition?
Please disregard this comment if you find this method more readable.

2025-01-02 23:59 UTC, dominicaligent requested changes

2025-01-02 23:59 UTC, dominicaligent commented on Plugin/Model/ReplacePasswordValidationRules.php
> +    public function aroundAddPasswordRules(
If you review the PR below, there are a couple of changes to the test scenarios. Do these changes impact the tests?

https://github.com/magento/magento2/pull/39319/files

2025-01-03 00:19 UTC, aligent-lturner commented on Model/DisableInactiveAdminAccounts.php
> +        $userCollection->addFieldToFilter('logdate', ['null' => true]);
I find the way `OR` conditions are handled to be a bit messy, so I did two separate collections for readability as suggested.

2025-01-03 00:21 UTC, aligent-lturner commented on Plugin/Model/ReplacePasswordValidationRules.php
> +    public function aroundAddPasswordRules(
Any change going in there would not be included in 2.4.6 or 2.4.7 (other than potentially via a quality patch.
I can see the validation.js script has been updated, so I can take a look at fixing that up too, though JS changes are always messier.
Changes to Magento's own tests are irrelevant, as we are only going to be running our own test cases.

2025-01-03 00:28 UTC, dominicaligent submitted a review, later dismissed

2025-01-06 00:01 UTC, dominicaligent approved these changes

2025-01-06 04:05 UTC, merged